#!/bin/bash

# Define your display names
EXT="HDMI-0"
INT="eDP-1"

# Check if HDMI is connected
STATUS=$(xrandr | grep "^$EXT connected")

if [ -n "$STATUS" ]; then
    xrandr --dpi 96 --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-4 --mode 2560x1440 --pos 1920x0 --rotate normal
else
    xrandr --output "$EXT" --off --output "$INT" --auto
fi
